### ISSUE TITLE
remove spaces

### ISSUE THREAD

**Issue by arlogriffiths** [arlogriffiths/idenk#1]
At [https://epigraphia.efeo.fr/nusantara/idenk/ind/rejected-data/](https://epigraphia.efeo.fr/nusantara/idenk/ind/rejected-data/), please remove spaces after first and before last parenthesis. See screenshot.

<img width="220" alt="Capture d’écran 2019-09-24 à 13 11 32" src="https://user-images.githubusercontent.com/835603/65506864-e4831000-decc-11e9-850f-c708f807b22d.png">

**Comment by vpaillusson** [comment]
spaces removing: done
