### ISSUE TITLE
delete the word "dari" several times (1)

### ISSUE THREAD

**Issue by arlogriffiths** [arlogriffiths/idenk#2]
Désolé, quelques défauts de style avaient échappé à mon attention.

Pour la page [https://epigraphia.efeo.fr/nusantara/idenk/ind/scope/](url)https://epigraphia.efeo.fr/nusantara/idenk/ind/scope/, il s'agit de:

hasil dari kerja sama >>  hasil kerja sama
Pokok dari data yang >> Pokok data yang

**Comment by vpaillusson** [comment]
c'est fait
