### ISSUE TITLE
edits to Indonesian text for Background

### ISSUE THREAD

**Issue by arlogriffiths** [arlogriffiths/idenk#3]
[https://epigraphia.efeo.fr/nusantara/idenk/ind/background/](https://epigraphia.efeo.fr/nusantara/idenk/ind/background/)

- replace the first paragraph by: "Kerja sama bilateral ini tercipta berdasarkan pengamatan bahwa setelah lebih dari dua abad kegiatan pengumpulan prasasti kuno di Indonesia dan negara-negara lain di kawasan Asia Tenggara Maritim, inventaris umum yang menyeluruh belum pernah dilakukan. Pengalaman di bidang sejenis dalam konteks epigrafi Asia Tenggara Daratan menunjukkan bahwa inventaris prasasti yang menghimpun informasi metadata terpenting dari setiap prasasti dalam korpus tertentu, seperti tempat penemuan, tempat penyimpanan, salinan atau foto, rujukan kepustakaan, juga golongan dan bahan artefak tempat prasasti dituliskan, ukurannya, jumlah baris, bahasa yang digunakan, serta dilengkapi dengan penentuan nomor referensi tetap, menjadi alat yang sangat diperlukan untuk pengaturan data semacam ini. 
     Prasasti adalah satu-satunya sumber lokal tertulis yang bersifat historis yang kita miliki sampai pertengahan abad ke-14 M. Inventaris pertama prasasti-prasasti kuno yang diterbitkan oleh R.M. Verbeek pada tahun 1891 (_Oudheden van Java_, h. 7–13), hanya berfokus pada prasasti berangka tahun dari pulau Jawa. Selanjutnya, Dinas Arkeologi Hindia Belanda melakukan inventarisasi temuan arkeologis yang diterbitkan dalam beberapa tahap. Dalam terbitan tersebut prasasti kadangkala menjadi bagian dalam inventaris benda purbakala lebih umum, sementara pembahasan terhadapnya hanya terbatas pada prasasti yang berangka tahun. Lihat daftar publikasi relevan berikut yang muncul antara 1911 dan 1923: ..."

- replace all cases of "pp." by "h."
- Gedateerde Inscriptions >> Gedateerde Inscripties

**Comment by vpaillusson** [comment]
c'est fait
